name: spotgrab
services:
  app:
    build: .
    image: thepangel/spotgrab:latest
    ports:
      - target: 8000
        published: "8000"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/Media/Music
        target: /music  
      - type: bind
        source: /DATA/AppData/spotgrab
        target: /public_downloads
    environment:
      - CLIENT_ID=your_spotify_client_id
      - CLIENT_SECRET=your_spotify_client_secret
      - FILE_CLEANUP_INTERVAL=1800
      - FILE_CLEANUP_MAX_AGE=3600
      - BITRATE=192k
    restart: unless-stopped
    labels:
      icon: https://cdn.jsdelivr.net/gh/thepangel/spotgrab/src/logo.svg
     

x-casaos:
  architectures:
    - amd64
    - arm64
  author: thepangel
  category: Media
  description:
    en_us: Web-based Spotify music downloader with real-time progress and direct download capability
  developer: thepangel
  icon: https://cdn.jsdelivr.net/gh/thepangel/spotgrab/src/logo.svg
  is_uncontrolled: false
  main: app
  port_map: "8000"
  store_app_id: spotgrab
  tagline:
    en_us: Download Spotify playlists and tracks with real-time progress
  thumbnail: https://cdn.jsdelivr.net/gh/thepangel/spotgrab/src/logo.svg
  title:
    en_us: spotGrab